---
- name: install k8s gateway api
  vars:
    ansible_python_interpreter: /opt/k8s_venv/bin/python
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    src: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
    state: present