---
# file: roles/controlplane/tasks/setup_linkerd.yaml

- name: Add linkerd chart repo
  kubernetes.core.helm_repository:
    name: linkerd-edge
    repo_url: "https://helm.linkerd.io/edge"

- name: Deploy linkerd CRDs
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: linkerd-crds
    chart_ref: linkerd-edge/linkerd-crds
    release_namespace: linkerd
    create_namespace: true
    state: absent # present | absent
    set_values:
      - value: installGatewayAPI=false

- name: ensures linkerd dir exists
  file: 
    path: "/tmp/linkerd"
    state: directory
    recurse: true

- name: Copy linkerd ca.crt
  ansible.builtin.copy:
    src: linkerd/ca.crt
    dest: /tmp/linkerd/ca.crt

- name: Copy linkerd issuer.crt
  ansible.builtin.copy:
    src: linkerd/issuer.crt
    dest: /tmp/linkerd/issuer.crt

- name: Copy linkerd issuer.key
  ansible.builtin.copy:
    src: linkerd/issuer.key
    dest: /tmp/linkerd/issuer.key

- name: Deploy linkerd
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: linkerd-control-plane
    chart_ref: linkerd-edge/linkerd-control-plane
    release_namespace: linkerd
    create_namespace: true
    state: absent # present | absent
    set_values:
      - value: identityTrustAnchorsPEM=/tmp/linkerd/ca.crt
        value_type: file
      - value: identity.issuer.tls.crtPEM=/tmp/linkerd/issuer.crt
        value_type: file
      - value: identity.issuer.tls.keyPEM=/tmp/linkerd/issuer.key
        value_type: file