---
# file: roles/nfs/tasks/setup_nfs_provisioner.yaml

- name: Add nfs-subdir-external-provisioner chart repo
  kubernetes.core.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

- name: Deploy nfs provisioner
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    kubeconfig: "{{ kubeconfig_path }}"
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: nfs-provisioner
    create_namespace: true
    state: absent # present | absent
    set_values:
      - value: nfs.server={{ tf_nfs_server_ip[0] }}
        value_type: string
      - value: nfs.path=/data
        value_type: string