- name: Check helm
  command: helm version --short
  register: helm_check
  ignore_errors: true
  changed_when: false


- name: Download Helm installer
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get-helm-3
    mode: '0755'
  when: helm_check.rc != 0


- name: Install Helm
  command: /tmp/get-helm-3
  environment:
    DESIRED_VERSION: "{{ helm_version }}"
    HELM_INSTALL_DIR: "{{ k8s_tools_install_dir }}"
  become: "{{ k8s_tools_become }}"
  when: helm_check.rc != 0