apiVersion: v1
kind: Pod
metadata:
  name: test-ceph-pod
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: ceph-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: ceph-vol
      persistentVolumeClaim:
        claimName: test-ceph-pvc
