k8s_tools_install_dir: /usr/local/bin
k8s_tools_become: true

# For none root install use below:
# k8s_tools_become: false
# k8s_tools_install_dir: "{{ ansible_env.HOME }}/.local/bin"


kubectl_version: v1.29.1
helm_version: v3.14.2
kustomize_version: v5.3.0
istio_version: 1.21.0